<?php

use Drupal\BehatEditorSauceLabs;

function behat_editor_saucelabs_permission() {
    $items['behat run saucelabs test'] = array(
        'title' => t('Can run a Saucelabs a test'),
        'description' => t('Can run a Saucelabs a test')
    );
    $items['behat admin saucelabs'] = array(
        'title' => t('Can admin Saucelabs'),
        'description' => t('Can  admin Saucelabs')
    );
    return $items;
}

function behat_editor_saucelabs_menu() {
    $path = drupal_get_path('module', 'behat_editor_saucelabs');
    $items['admin/behat/saucelabs/run/%/%'] = array(
        'page callback' => array('behat_editor_saucelabs_run'),
        'page arguments' => array(4,5),
        'file' => 'behat_editor_saucelabs_run.inc',
        'access arguments' => array('behat run saucelabs test'),
        'file path' => "$path/includes"
    );
    /* allow jquery to get data about jobs status */
    $items['admin/behat/saucelabs/jobs'] = array(
        'page callback' => array('behat_editor_saucelabs_jobs'),
        'access arguments' => array('behat run saucelabs test'),
    );

    $items['admin/config/development/behat_saucelabs'] = array(
        'page callback' => array('drupal_get_form'),
        'page arguments' => array('behat_editor_saucelabs_admin_form'),
        'access arguments' => array('behat admin saucelabs'),
        'description' => "Setup Behat to integrate with SauceLabs",
        'title' => 'Behat Editor SauceLabs Settings',
        'file path' => "$path/includes",
        'file' => 'behat_editor_saucelabs_admin_form.inc',
    );
    return $items;
}

function behat_editor_saucelabs_form_alter(&$form, $form_state, $form_id) {
    $forms = array('behat_editor_view_form', 'behat_editor_edit_form', 'behat_editor_add_form');
    if(in_array($form_id, $forms)) {
        composer_manager_register_autoloader();
        if (!class_exists('Drupal\BehatEditorSauceLabs\Wrapper')) {
            $message = t('SauceLabs Wrapper not found.');
            throw new \RuntimeException($message);
        }

        $username = variable_get('behat_editor_saucelabs_username', '');
        $api_key = variable_get('behat_editor_saucelabs_api', '');

        $check_connection = new Drupal\BehatEditorSauceLabs\Wrapper($username, $api_key);
        $connected = $check_connection->connectTest();

        if(isset($connected['error']) || empty($username) || empty($api_key)) {
            $disabled = 'disabled';
            drupal_set_message(t("Saucelabs connection error: :error The Saucelabs button will be disabled till resolved.", array(':error' => $connected['error'])), 'error');
            drupal_set_message(t("You can configure SauceLabs here !here", array('!here' => l('configure', 'admin/config/development/behat_saucelabs'))), 'info');
        } else {
            $disabled = '';
        }

        $module = arg(3);
        $filename = arg(4);
        $path = drupal_get_path('module', 'behat_editor_saucelabs');
        $form['#attached']['js']['behat_editor_saucelabs_run'] = $path . '/js/behat_editor_saucelabs_run.js';

        $form['actions']['saucelabs_run'] = array(
            '#type' => 'link',
            '#title' => 'Run on Sauce Labs',
            '#name' => 'sauce_labs',
            '#href' => "admin/behat/saucelabs/run/$module/$filename",
            '#attributes' => array('class' => array('sauce', 'btn', 'btn-success', "$disabled"))
        );
    }
}



function behat_editor_saucelabs_jobs() {
    composer_manager_register_autoloader();
    if (!class_exists('Drupal\BehatEditorSauceLabs\Wrapper')) {
        $message = t('SauceLabs Wrapper not found.');
        drupal_json_output(array('error' => 1, 'message' => $message));
        exit();
    }

    $username = variable_get('behat_editor_saucelabs_username', '');
    $api_key = variable_get('behat_editor_saucelabs_api', '');
    $check_connection = new Drupal\BehatEditorSauceLabs\Wrapper($username, $api_key);
    $summary = $check_connection->jobsSummary();
    drupal_json_output($summary);
    exit();
}

