<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs\\' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Tokenizer\\' => array($vendorDir . '/alnutile/token_file_creator/lib'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Symfony\\Component\\Serializer\\' => array($vendorDir . '/symfony/serializer'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'Symfony\\Component\\CssSelector\\' => array($vendorDir . '/symfony/css-selector'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'OrangeDigital\\BusinessSelectorExtension' => array($vendorDir . '/orangedigital/business-selector-extension/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Drupal\\Tokenizer' => array($baseDir . '/src'),
    'Behat\\MinkExtension' => array($vendorDir . '/behat/mink-extension/src'),
    'Behat\\Mink' => array($vendorDir . '/behat/mink/src'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'Behat\\Behat' => array($vendorDir . '/behat/behat/src'),
);
